version: 2

sources:
   - name: Raw    
     database: wagon-test-485210
     schema: gz_raw_data
     loader: bigquery
     description: test analyse for Wagon
     tables:
       - name: product #alias
         identifier: raw_gz_product
         description: list of the product of product / we have the product id and purchase price
         columns :
          - name : products_id
            description: Primary Keys
            tests :
              - unique
              - not_null
       - name: sales #alias
         identifier: raw_gz_sales    
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         columns :
          - name: date_date,
          - name: orders_id,
          - name: pdt_id,
          - name: revenue,
          - name: quantity
         tests : 
           - unique : 
              column_name: "(orders_id || '-' || pdt_id)" 
              
       - name: ship #alias  
         identifier: raw_gz_ship
         description: amount of shiping of Greenweez
         columns :
          - name : orders_id
            description: Primary Key
            tests :
              - unique
              - not_null 

